### ISSUE TITLE
[go-livepeer] Nil pointer with ImageToVideo handler on O 

### ISSUE THREAD

**Issue by yondonfu** [livepeer/ai-worker#26]
```
I0202 15:58:04.980337       1 ai_http.go:129] clientIP=REDACTED Received ImageToVideo request imageSize=622849 model_id=stabilityai/stable-video-diffusion-img2vid-xt
2024/02/02 15:58:05 http2: panic serving REDACTED: runtime error: invalid memory address or nil pointer dereference
goroutine 1843 [running]:
net/http.(*http2serverConn).runHandler.func1()
        /usr/local/go/src/net/http/h2_bundle.go:6186 +0x13b
panic({0x3b6d40?, 0x31478d0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/livepeer/go-livepeer/core.(*LivepeerNode).imageToVideo(0xc0005029c0, {0xb04710, 0xc00063ab40}, {0x0, 0x0, {0xc0006ba360, {0x0, 0x0, 0x0}, {0x0, ...}}, ...})
        /src/core/orchestrator.go:906 +0xb7
github.com/livepeer/go-livepeer/core.(*orchestrator).ImageToVideo(0x4e?, {0xb04710?, 0xc00063ab40?}, {0x0, 0x0, {0xc0006ba360, {0x0, 0x0, 0x0}, {0x0, ...}}, ...})
        /src/core/orchestrator.go:117 +0x58
github.com/livepeer/go-livepeer/server.startAIServer.(*lphttp).ImageToVideo.func4({0xaffb90, 0xc0007ae008}, 0xb?)
        /src/server/ai_http.go:132 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc00090a100?, {0xaffb90?, 0xc0007ae008?}, 0xc000f12a00?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/oapi-codegen/nethttp-middleware.OapiRequestValidatorWithOptions.func1.1({0xaffb90, 0xc0007ae008}, 0x1?)
        /go/pkg/mod/github.com/oapi-codegen/nethttp-middleware@v1.0.1/oapi_validate.go:64 +0xed
net/http.HandlerFunc.ServeHTTP(0x18fe59e?, {0xaffb90?, 0xc0007ae008?}, 0x1ac84df?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0xc000268e10?, {0xaffb90, 0xc0007ae008}, 0xc00090a100)
        /usr/local/go/src/net/http/server.go:2514 +0x142
github.com/livepeer/go-livepeer/server.(*lphttp).ServeHTTP(0xc0000e6ea0, {0xaffb90, 0xc0007ae008}, 0xc00090a100)
        /src/server/rpc.go:176 +0xa5
net/http.serverHandler.ServeHTTP({0xc00097be88?}, {0xaffb90?, 0xc0007ae008?}, 0xc000574800?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.initALPNRequest.ServeHTTP({{0xb04710?, 0xc000f88db0?}, 0xc00039ae00?, {0xc0007661e0?}}, {0xaffb90, 0xc0007ae008}, 0xc00090a100)
        /usr/local/go/src/net/http/server.go:3546 +0x231
net/http.(*http2serverConn).runHandler(0x34dd9e0?, 0x0?, 0x0?, 0xc000126120?)
        /usr/local/go/src/net/http/h2_bundle.go:6193 +0xbb
created by net/http.(*http2serverConn).scheduleHandler in goroutine 1148
        /usr/local/go/src/net/http/h2_bundle.go:6128 +0x21d
```

**Comment by yondonfu** [comment]
Fixed by https://github.com/livepeer/ai-worker/commit/823caeaa265f11727a181b63cda46325ca7ca611
